//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWinForm3Layer.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CTHoaDons = new HashSet<CTHoaDon>();
            this.KHACHHANGs = new HashSet<KHACHHANG>();
        }
    
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public string MALOAI { get; set; }
        public Nullable<int> SL { get; set; }
        public string MATH { get; set; }
        public Nullable<int> LUOTMUA { get; set; }
        public Nullable<bool> BIXOA { get; set; }
        public Nullable<int> GiaBan { get; set; }
        public Nullable<int> GiaMua { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHoaDon> CTHoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHACHHANG> KHACHHANGs { get; set; }
        public virtual LOAI LOAI { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
    }
}
